image: node:latest
tags:
  - "tokend"


stages:
  - deploy

pages:
  stage: deploy
  script:
  - yarn install
  - yarn build
  - mv ./build ./public
  artifacts:
    paths:
    - public
  only:
    - main
