image: node:16.17.0-alpine
tags:
  - "tokend"

stages:
  - deploy

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - main
