default:
  image: node:18.11.0
  tags:
    - "tokend"

stages:
  - deploy

pages:
  stage: deploy
  script:
    - yarn install
    - yarn lint
    - yarn typecheck
    - yarn build
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - main
