default:
  image: node:18.11.0
  tags:
    - "tokend"

stages:
  - test
  - deploy

test:
  stage: test
  script:
   - yarn install --frozen-lockfile
   - yarn lint
   - yarn typecheck
  only:
   - merge_requests

deploy:
  stage: deploy
  script:
    - yarn install --frozen-lockfile --production
    - yarn build
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - main
