on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  IMAGE_NAME: ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME
  URL: "https://staging.docs.rarimo.com"
  DOMAIN: staging.docs.rarimo.com

jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Run echo
        run: |
          werf version
          docker version
          echo $GITHUB_REPOSITORY
          echo $GITHUB_REF_NAME
      - name: Run Build
        run: |
          . $(werf ci-env github --as-file)
          werf export --dev web --tag $IMAGE_NAME

  # deploy:
  #     name: Deploy
  #     needs: converge
  #     runs-on: ubuntu-latest
  #     steps:
  #       - name: Checkout code
  #         uses: actions/checkout@v3
  #         with:
  #           fetch-depth: 0
  #       - name: ConfigCreate
  #         run: |
  #           mkdir ~/.kube/
  #           echo "${{ secrets.K8SCONFIG_MAIN }}" | base64 -d > config
  #           mv config ~/.kube/
  #           helm upgrade -i "docs" ".helm" --set global.IngressDomain=staging.${DOMAIN} --set "image.repository=ghcr.io/${$GITHUB_REPOSITORY}" --set "image.tag=${GITHUB_SHA}" --create-namespace --namespace docs-prod

  #           kubectl set image deployment rarimo-web template=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME -n robotornot
